# List of 110+ social media and developer platforms for OSINT username mapping.
# Each entry: name, url_template, error_codes, error_keywords, category
# Categories: social, dev, gaming, creative, music, financial, security, other

SITES = [
    # ---- SOCIAL MEDIA ----
    {"name": "Instagram", "url_template": "https://www.instagram.com/{}/", "error_codes": [404], "error_keywords": ["Page Not Found", "The link you followed may be broken"], "category": "social"},
    {"name": "TikTok", "url_template": "https://www.tiktok.com/@{}", "error_codes": [404], "error_keywords": ["Could not find this user"], "category": "social"},
    {"name": "Reddit", "url_template": "https://www.reddit.com/user/{}", "error_codes": [404], "error_keywords": ["page not found", "Sorry, nobody on Reddit goes by that name"], "category": "social"},
    {"name": "Pinterest", "url_template": "https://www.pinterest.com/{}/", "error_codes": [404], "error_keywords": ["User not found", "404"], "category": "social"},
    {"name": "Tumblr", "url_template": "https://{}.tumblr.com/", "error_codes": [404], "error_keywords": ["There's nothing here.", "This Tumblr doesn't exist"], "category": "social"},
    {"name": "Snapchat", "url_template": "https://www.snapchat.com/add/{}", "error_codes": [404], "error_keywords": ["Sorry, we couldn't find", "404"], "category": "social"},
    {"name": "Bluesky", "url_template": "https://bsky.app/profile/{}", "error_codes": [404], "error_keywords": ["Profile not found", "404", "could not be found"], "category": "social"},
    {"name": "Mastodon", "url_template": "https://mastodon.social/@{}", "error_codes": [404], "error_keywords": ["The page you are looking for isn't here", "404"], "category": "social"},
    {"name": "Flickr", "url_template": "https://www.flickr.com/photos/{}/", "error_codes": [404], "error_keywords": ["The page you requested cannot be found", "404"], "category": "social"},
    {"name": "Linktree", "url_template": "https://linktr.ee/{}", "error_codes": [404], "error_keywords": ["Page not found", "404"], "category": "social"},
    {"name": "Medium", "url_template": "https://medium.com/@{}", "error_codes": [404], "error_keywords": ["PAGE NOT FOUND", "404"], "category": "social"},
    {"name": "Substack", "url_template": "https://{}.substack.com", "error_codes": [404], "error_keywords": ["404", "not found"], "category": "social"},
    {"name": "Blogger", "url_template": "https://{}.blogspot.com", "error_codes": [404], "error_keywords": ["Sorry, the page you were looking for", "not found"], "category": "social"},
    {"name": "About.me", "url_template": "https://about.me/{}", "error_codes": [404], "error_keywords": ["404", "Not Found"], "category": "social"},
    {"name": "Gravatar", "url_template": "https://en.gravatar.com/{}", "error_codes": [404], "error_keywords": ["User not found"], "category": "social"},
    {"name": "Ello", "url_template": "https://ello.co/{}", "error_codes": [404], "error_keywords": ["404"], "category": "social"},
    {"name": "Twitch", "url_template": "https://www.twitch.tv/{}", "error_codes": [404], "error_keywords": ["Sorry. Unless you've got a time machine"], "category": "social"},
    # ---- DEVELOPMENT & TECH ----
    {"name": "GitHub", "url_template": "https://github.com/{}", "error_codes": [404], "error_keywords": ["Not Found", "Find code, projects, and people"], "category": "dev"},
    {"name": "GitLab", "url_template": "https://gitlab.com/{}", "error_codes": [404], "error_keywords": ["Sign in", "Register", "Not Found"], "category": "dev"},
    {"name": "Bitbucket", "url_template": "https://bitbucket.org/{}/", "error_codes": [404], "error_keywords": ["404", "Resource not found"], "category": "dev"},
    {"name": "DockerHub", "url_template": "https://hub.docker.com/u/{}", "error_codes": [404], "error_keywords": ["Object not found", "404"], "category": "dev"},
    {"name": "PyPI", "url_template": "https://pypi.org/user/{}", "error_codes": [404], "error_keywords": ["Not Found"], "category": "dev"},
    {"name": "NPM", "url_template": "https://www.npmjs.com/~{}", "error_codes": [404], "error_keywords": ["404 Not Found"], "category": "dev"},
    {"name": "Codepen", "url_template": "https://codepen.io/{}", "error_codes": [404], "error_keywords": ["404", "doesn't exist"], "category": "dev"},
    {"name": "Dev.to", "url_template": "https://dev.to/{}", "error_codes": [404], "error_keywords": ["The page you were looking for doesn't exist"], "category": "dev"},
    {"name": "HackerNews", "url_template": "https://news.ycombinator.com/user?id={}", "error_codes": [200], "error_keywords": ["No such user"], "category": "dev"},
    {"name": "SourceForge", "url_template": "https://sourceforge.net/u/{}/profile", "error_codes": [404], "error_keywords": ["not found"], "category": "dev"},
    {"name": "SpeakerDeck", "url_template": "https://speakerdeck.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "dev"},
    {"name": "Launchpad", "url_template": "https://launchpad.net/~{}", "error_codes": [404], "error_keywords": ["does not exist"], "category": "dev"},
    {"name": "Kaggle", "url_template": "https://www.kaggle.com/{}", "error_codes": [404], "error_keywords": ["404", "not found"], "category": "dev"},
    {"name": "Codeforces", "url_template": "https://codeforces.com/profile/{}", "error_codes": [404], "error_keywords": ["handle not found"], "category": "dev"},
    {"name": "LeetCode", "url_template": "https://leetcode.com/u/{}/", "error_codes": [404], "error_keywords": ["404"], "category": "dev"},
    {"name": "HackerEarth", "url_template": "https://www.hackerearth.com/@{}", "error_codes": [404], "error_keywords": ["404"], "category": "dev"},
    {"name": "Pastebin", "url_template": "https://pastebin.com/u/{}", "error_codes": [404], "error_keywords": ["404"], "category": "dev"},
    {"name": "ProductHunt", "url_template": "https://www.producthunt.com/@{}", "error_codes": [404], "error_keywords": ["Page Not Found"], "category": "dev"},
    {"name": "Codecademy", "url_template": "https://www.codecademy.com/profiles/{}", "error_codes": [404], "error_keywords": ["404"], "category": "dev"},
    {"name": "Hackaday", "url_template": "https://hackaday.io/{}", "error_codes": [404], "error_keywords": ["404", "not found"], "category": "dev"},
    {"name": "Keybase", "url_template": "https://keybase.io/{}", "error_codes": [404], "error_keywords": ["404"], "category": "dev"},
    # ---- SECURITY & CTF ----
    {"name": "TryHackMe", "url_template": "https://tryhackme.com/p/{}", "error_codes": [404], "error_keywords": ["404"], "category": "security"},
    {"name": "HackTheBox", "url_template": "https://forum.hackthebox.eu/u/{}", "error_codes": [404], "error_keywords": ["404"], "category": "security"},
    # ---- GAMING ----
    {"name": "Steam", "url_template": "https://steamcommunity.com/id/{}", "error_codes": [404], "error_keywords": ["The specified profile could not be found"], "category": "gaming"},
    {"name": "Roblox", "url_template": "https://www.roblox.com/user.aspx?username={}", "error_codes": [404], "error_keywords": ["Page Not Found"], "category": "gaming"},
    {"name": "Chess.com", "url_template": "https://www.chess.com/member/{}", "error_codes": [404], "error_keywords": ["Page Not Found"], "category": "gaming"},
    {"name": "MyAnimeList", "url_template": "https://myanimelist.net/profile/{}", "error_codes": [404], "error_keywords": ["404"], "category": "gaming"},
    {"name": "Trakt", "url_template": "https://trakt.tv/users/{}", "error_codes": [404], "error_keywords": ["404"], "category": "gaming"},
    {"name": "Fandom", "url_template": "https://www.fandom.com/u/{}", "error_codes": [404], "error_keywords": ["404"], "category": "gaming"},
    {"name": "Scratch", "url_template": "https://scratch.mit.edu/users/{}", "error_codes": [404], "error_keywords": ["404"], "category": "gaming"},
    {"name": "Itch.io", "url_template": "https://{}.itch.io", "error_codes": [404], "error_keywords": ["404", "page not found"], "category": "gaming"},
    # ---- CREATIVE & ART ----
    {"name": "Dribbble", "url_template": "https://dribbble.com/{}", "error_codes": [404], "error_keywords": ["404", "Whoops, that page is gone"], "category": "creative"},
    {"name": "Behance", "url_template": "https://www.behance.net/{}", "error_codes": [404], "error_keywords": ["404", "Oops! We can't find this page"], "category": "creative"},
    {"name": "DeviantArt", "url_template": "https://www.deviantart.com/{}", "error_codes": [404], "error_keywords": ["404 Not Found"], "category": "creative"},
    {"name": "ArtStation", "url_template": "https://www.artstation.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    {"name": "Pixiv", "url_template": "https://www.pixiv.net/users/{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    {"name": "Redbubble", "url_template": "https://www.redbubble.com/people/{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    {"name": "Pexels", "url_template": "https://www.pexels.com/@{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    {"name": "Unsplash", "url_template": "https://unsplash.com/@{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    {"name": "Giphy", "url_template": "https://giphy.com/{}", "error_codes": [404], "error_keywords": ["404 Not Found"], "category": "creative"},
    {"name": "Wattpad", "url_template": "https://www.wattpad.com/user/{}", "error_codes": [404], "error_keywords": ["User Not Found"], "category": "creative"},
    {"name": "Letterboxd", "url_template": "https://letterboxd.com/{}/", "error_codes": [404], "error_keywords": ["This page can't be found"], "category": "creative"},
    {"name": "Issuu", "url_template": "https://issuu.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    {"name": "Goodreads", "url_template": "https://www.goodreads.com/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "creative"},
    {"name": "Scribd", "url_template": "https://www.scribd.com/user/{}", "error_codes": [404], "error_keywords": ["Page Not Found"], "category": "creative"},
    {"name": "Etsy", "url_template": "https://www.etsy.com/people/{}", "error_codes": [404], "error_keywords": ["404"], "category": "creative"},
    # ---- MUSIC & AUDIO/VIDEO ----
    {"name": "SoundCloud", "url_template": "https://soundcloud.com/{}", "error_codes": [404], "error_keywords": ["Oops, we can't find that user", "404"], "category": "music"},
    {"name": "Spotify", "url_template": "https://open.spotify.com/user/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "music"},
    {"name": "Last.fm", "url_template": "https://www.last.fm/user/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "music"},
    {"name": "Bandcamp", "url_template": "https://bandcamp.com/{}", "error_codes": [404], "error_keywords": ["not found"], "category": "music"},
    {"name": "Mixcloud", "url_template": "https://www.mixcloud.com/{}/", "error_codes": [404], "error_keywords": ["Page Not Found"], "category": "music"},
    {"name": "ReverbNation", "url_template": "https://www.reverbnation.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "music"},
    {"name": "Discogs", "url_template": "https://www.discogs.com/user/{}", "error_codes": [404], "error_keywords": ["404"], "category": "music"},
    {"name": "Vimeo", "url_template": "https://vimeo.com/{}", "error_codes": [404], "error_keywords": ["Sorry, we couldn't find that page"], "category": "music"},
    {"name": "DailyMotion", "url_template": "https://www.dailymotion.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "music"},
    # ---- FINANCIAL & SUPPORT ----
    {"name": "Patreon", "url_template": "https://www.patreon.com/{}", "error_codes": [404], "error_keywords": ["404 Not Found", "page not found"], "category": "financial"},
    {"name": "BuyMeACoffee", "url_template": "https://www.buymeacoffee.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "financial"},
    {"name": "Ko-Fi", "url_template": "https://ko-fi.com/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "financial"},
    {"name": "Gumroad", "url_template": "https://{}.gumroad.com", "error_codes": [404], "error_keywords": ["page not found"], "category": "financial"},
    {"name": "Kickstarter", "url_template": "https://www.kickstarter.com/profile/{}", "error_codes": [404], "error_keywords": ["404"], "category": "financial"},
    {"name": "Venmo", "url_template": "https://venmo.com/u/{}", "error_codes": [404], "error_keywords": ["404", "Page not found"], "category": "financial"},
    {"name": "Freelancer", "url_template": "https://www.freelancer.com/u/{}", "error_codes": [404], "error_keywords": ["not found"], "category": "financial"},
    {"name": "Fiverr", "url_template": "https://www.fiverr.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "financial"},
    {"name": "AngelList", "url_template": "https://wellfound.com/u/{}", "error_codes": [404], "error_keywords": ["404"], "category": "financial"},
    # ---- OTHER / MISC ----
    {"name": "Duolingo", "url_template": "https://www.duolingo.com/profile/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "other"},
    {"name": "Tripadvisor", "url_template": "https://www.tripadvisor.com/Profile/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "other"},
    {"name": "OpenStreetMap", "url_template": "https://www.openstreetmap.org/user/{}", "error_codes": [404], "error_keywords": ["No user with the name"], "category": "other"},
    {"name": "Disqus", "url_template": "https://disqus.com/by/{}/", "error_codes": [404], "error_keywords": ["404"], "category": "other"},
    {"name": "IFTTT", "url_template": "https://ifttt.com/p/{}", "error_codes": [404], "error_keywords": ["404"], "category": "other"},
    {"name": "Instructables", "url_template": "https://www.instructables.com/member/{}/", "error_codes": [404], "error_keywords": ["404: Page Not Found"], "category": "other"},
    {"name": "Slideshare", "url_template": "https://www.slideshare.net/{}", "error_codes": [404], "error_keywords": ["404"], "category": "other"},
    {"name": "Houzz", "url_template": "https://www.houzz.com/user/{}", "error_codes": [404], "error_keywords": ["Page not found"], "category": "other"},
    {"name": "WeHeartIt", "url_template": "https://weheartit.com/{}", "error_codes": [404], "error_keywords": ["404"], "category": "other"},
]

